# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: required
os:
  - linux
sudo: required
julia:
  - 1.1.0
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("OptiMimi"); Pkg.test("OptiMimi"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("OptiMimi.jl")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
